### ISSUE TITLE
User-can-create-a-custom-list

### ISSUE THREAD

**Issue by CristoferMar** [CristoferMar/Final-Project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be able to create a new list, with their own title.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![1A Feature - Final Project](https://user-images.githubusercontent.com/82407007/126405659-f0e56280-20f3-4aeb-ae9d-20b162142df0.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Create tables and their relationships on dbDesigner
- [x] Update `schema.sql` to accommodate for users, lists, dates, history
- [x] Hard code user 1 into data.sql

### ☁️ Server

- [x] Update `server/index.js` to handle POST requests with two argument, listName & userId
- [x] Verfy listName agrument is a valid entry
- [x] Send SQL duqery to add list name, returning list name & listId
- [x] Set response to send JSON object containing the listName and listId
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component that has the modal appear with a form for the user to input the new list name
- [x] Add functionality to handle listName input
- [x] Add functionality to handle submit
- [x] handle submit sends a fetch request to the server, with the listName and the userId

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
