### ISSUE TITLE
User can view their own lists

### ISSUE THREAD

**Issue by CristoferMar** [CristoferMar/Final-Project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![1 Feature - Final Project](https://user-images.githubusercontent.com/82407007/126403059-9f0f3f49-a2f7-4d73-9e6b-53495c80f3da.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] none

### ☁️ Server

- [x] Update `server/index.js` to listen for GET requests, provided the userId
- [x] Query DB to select all lists belonging to the requested User
- [x] return an array of all the lists the user has
- [x] catch any errors
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to produce a navbar
- [x] Add functionality for a drawer to be rendered to the page if the user clicks on the user icon
- [x] Create and style react elements visible when user views their lists
- [x] Create a function to map through all the lists the user has, in the returned GET, generating the lists of listNames
- [x] Create a component to display the listNames as individual react elements.
- [x] Create a component to display if the user has no list titles
- [x] Assign each different page a #location, for switching in between pages.
- [x] Add functionality to render different pages, depending on the current location or designated destination
- [x] Add functionality to allows the user to swap from their "View Lists" page to their "Create List" page

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by CristoferMar** [comment]
![Feature#2 User-can-view-their-own-lists](https://user-images.githubusercontent.com/82407007/127221900-271586de-05dd-4308-86f7-b4e78a4e13a4.gif)
![Feature#2 Mobile User-can-view-their-own-lists](https://user-images.githubusercontent.com/82407007/127221905-811305f4-ce7a-470d-b32d-bad0be0a7336.gif)
