### ISSUE TITLE
User can add date ideas to their lists

### ISSUE THREAD

**Issue by CristoferMar** [CristoferMar/Final-Project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![2 Feature - Final Project](https://user-images.githubusercontent.com/82407007/126403246-73d69342-a0f4-4295-b361-a5ca4c79c534.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Add a column to the dates table to include a boolean for whether or not the specific date idea is active not.

### ☁️ Server

- [x] Update `server/index.js` to receive POST requests with userId, price, dateTitle
- [x] check if all required arguments exist.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to display new date form
- [x] Add event listeners for changes on each form input textbox
- [x] Add an event listener for submitting and canceling on the form
- [x] On submit event listener, include fetch request with required fields for the server to properly work.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
