### ISSUE TITLE
User-can-generate-a-date-idea-with-a-price-filter

### ISSUE THREAD

**Issue by CristoferMar** [CristoferMar/Final-Project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![4 Feature - Final Project](https://user-images.githubusercontent.com/82407007/126403672-1818c4cc-c253-438c-a44a-c361736c6ac4.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] None

### ☁️ Server

- [x] Update `server/index.js` to receive a GET request, given a user name
- [x] Return an array with the list names belonging to the user and the length of each list
- [x] If possible, return an object containing the list names and their available costs
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client
- [x] Update `server/index.js` to receive a GET request to handle a different get request, given a listid and the costAmount
- [x] Return an object with the dateTitle, the dateId and a timeStamp of when the date was generated
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] With more than one page now available, add a navigation drawer to the app, for user to browse its account
- [x] Create a component to render a form for users to fill out
- [x] Add a fetch request to componentDidMount to get all the listTitles associated with a given user
- [x] Add a handleSubmit event listener to fetch one random item on the list, providing the costAmount and listId
- [x] Create a component to render after a user generates a form

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
