### ISSUE TITLE
User can save the date idea into their date history

### ISSUE THREAD

**Issue by CristoferMar** [CristoferMar/Final-Project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/82407007/133866005-6d59b29f-35f1-4fbb-9451-dd3aa771bc51.png)
![image](https://user-images.githubusercontent.com/82407007/133866025-15e5f51d-7d31-40fa-b23f-9e21779aef5a.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] none

### ☁️ Server

- [x] created post request for adding items to history
- [x] Test with HTTPie
- [x] created get request for pulling users history
- [x] Test with HTTPie

### ⚡ Client

- [x] Create a component display user's history
- [x] Style page to best suit page
- [x] add logic for hash routing to the history page
- [x] add functionality to date generated page for sending post request to history table
- [x] add fetch request on componentDidMount for history page to collect history data
- [x] add functionality to convert each item's time stamp to a passing time in sec, min, days, etc
- [x] map through each item to create readable elements on the page

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
