### ISSUE TITLE
User-can-deactivate-certain-date-ideas-for-the-next-random-draw

### ISSUE THREAD

**Issue by CristoferMar** [CristoferMar/Final-Project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![6 Feature - Final Project](https://user-images.githubusercontent.com/82407007/134260257-6678b0ea-c62b-4edf-8326-14fa986c6ef1.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] none

### ☁️ Server

- [x] Update `server/index.js` to to process a patch request for toggling isActive in the row
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Creat new component dedicated to generating one list item
- [x] Add the checked or unchecked box to each item, depending on isActive status
- [x] Add logic to manipulate appearance of individual list items, depending on isActive status
- [x] Add event listener to list item for updating the current apperance
- [x] add fetch request in event listener to sent patch to server and update the DB

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
