### ISSUE TITLE
User can sign Up

### ISSUE THREAD

**Issue by CristoferMar** [CristoferMar/Final-Project#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![7 Feature - Final Project](https://user-images.githubusercontent.com/82407007/126404351-16cc387d-e6c9-4775-99e8-4d8aacbd17cb.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] none

### ☁️ Server

- [x] Update `server/index.js` handle post request, while hashing password before adding to db
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a new class for the landing page
- [x] Add path route handler for Landing-Page of empty string
- [x] Add styling and page layout for starting page
- [x] Created log/sign up component
- [x] Link landing page to sign-up page and log-in page
- [x] Exclude sign-up and log-in pages from navbar
- [x] Create styling and layout for Create Account form
- [x] Create registration form / log in form

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
