### ISSUE TITLE
User can sign In

### ISSUE THREAD

**Issue by CristoferMar** [CristoferMar/Final-Project#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![8 Feature - Final Project](https://user-images.githubusercontent.com/82407007/126404432-70c085c0-cb1c-4438-a71a-fedb244c1ea6.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] none

### ☁️ Server

- [x] Update `server/index.js` to use authorization middleware after sign-in/sign-up
- [x] Test with HTTPie
- [x] Add userId deconstruction for each API call, based on JWT payload
- [x] Add userId db query condition in each API call from JWT payload

### ⚡ Client

- [x] Create log in page
- [x] When logged in, store JWT & user name into local storage
- [x] When a user is logged in, redirect to the User's list page
- [x] If user signs out, clear local data and navigate to landing page

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
